/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UserOpt */

#ifndef _Included_UserOpt
#define _Included_UserOpt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UserOpt
 * Method:    findUser
 * Signature: (Ljava/lang/String;)LUser;
 */
JNIEXPORT jobject JNICALL Java_UserOpt_findUser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     UserOpt
 * Method:    saveUser
 * Signature: (LUser;)V
 */
JNIEXPORT void JNICALL Java_UserOpt_saveUser
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
