/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_createw_jnitest_UserOpt */

#ifndef _Included_com_createw_jnitest_UserOpt
#define _Included_com_createw_jnitest_UserOpt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_createw_jnitest_UserOpt
 * Method:    getUser
 * Signature: (Ljava/lang/String;)Lcom/createw/jnitest/User;
 */
JNIEXPORT jobject JNICALL Java_com_createw_jnitest_UserOpt_getUser
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_createw_jnitest_UserOpt
 * Method:    saveUser
 * Signature: (Lcom/createw/jnitest/User;)V
 */
JNIEXPORT void JNICALL Java_com_createw_jnitest_UserOpt_saveUser
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
